version: '3'
services:

  nginx:
    image: nginx:latest
    restart: always
    container_name: splash_nginx
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - splash
    ports:
      - 8051:8051

  splash:
    image: scrapinghub/splash
    container_name: splash_splash
    ports:
      - 8050:8050

